# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f13575abd331a727fee92c5048141acbb482fa5bbc9bca67223be9f8ebb4159f80c4bf6fc881f80fda93ef85771ba15dfa8948c52e42efb324d002369da4c08

test:
  secret_key_base: 899c91780e4ce815e284d9ad0bc25deeff78c095e59593726e33d1d3717ace6c6441e72b5977c42fc2b536b9bc70cdc1ace2b60c9dc652f66e255943e3b90ccb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
